# -*- coding: utf-8 -*-
"""511061236魏郁軒

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16SZTACicqNmfB6fnxbBemCPrw77PTRMz
"""

animal1 = "cat"
animal2 = "dog"
print(animal1 + " & " + animal2)